import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Topbar from "@/components/Topbar";
import ContextProvider from "@/hooks/ContextProvider";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import { SolNFTContextProvider } from "@/hooks/SolNFTContextProvider";

import "react-multi-carousel/lib/styles.css";
import Providers from "@/lib/providers";
import { NFTContextProvider } from "@/hooks/NFTContextProvider";
import 'react-loading-skeleton/dist/skeleton.css'

const inter = Inter({ subsets: ["latin"], weight: ["400", "900"] });

export const metadata: Metadata = {
  icons: "logo.webp",
  title: "Chimpzee - NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <ContextProvider>
            <NFTContextProvider>
              <SolNFTContextProvider>
                <div className="relative  bg-[url('/background2.png')] w-screen min-h-screen bg-cover">
                  <div className="bg-black/60">
                    <Topbar />
                    <div className="pt-[100px]">
                      {children}
                    </div>
                    <ToastContainer autoClose={10000} />
                    <Footer />
                  </div>
                </div>
              </SolNFTContextProvider>
            </NFTContextProvider>
          </ContextProvider>
        </body>
      </Providers>
    </html>
  );
}
